name: gits_responsive
description: A Flutter package for building responsive Flutter applications with support for breakpoints on mobile, tablet, and desktop.
version: 0.0.1
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/flutter-library/tree/main/packages/gits_responsive

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
