name: gits_http
description: Future-based library for making HTTP requests modified from http package.
version: 3.1.3
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/flutter-library/tree/main/packages/gits_http

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.2
  uuid: ^4.2.2
  equatable: ^2.0.5
  logger: ^2.0.2+1
  hive: ^2.2.3
  path_provider: ^2.1.1

  gits_inspector: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
